### ISSUE TITLE
use_gzip middleware wrong order

### ISSUE THREAD

**Issue by BohdanZhmud** [SaturnFramework/Saturn.Template#12]
Should not "use_gzip" function call be placed before "use_router Router.appRouter"?
As far as I see at this point it is not doing any compression.
I believe it should come after global error handler but before any other middleware.

see also https://github.com/aspnet/Docs/issues/2516

**Comment by rmunn** [comment]
The `use_router` call is special, and isn't processed in the same order as the configuration settings like `use_gzip`. See the `Run()` method in https://github.com/SaturnFramework/Saturn/blob/master/src/Saturn/Application.fs for all the details, but the gist of it is that all the other app configurations will be processed first, and then the final call to the `IApplicationBuilder` will be `app.UseGiraffe router`. So the router could be defined first, last, or in the middle of the other config options, and it wouldn't matter.

**Comment by BohdanZhmud** [comment]
I actually tested it with static content response and it was not compressed.
It is probably because use_gzip comes after use static

"use_static "static"
    use_gzip"
https://github.com/SaturnFramework/Saturn.Template/blob/master/Content/src/SaturnServer/Program.fs

The reason I proposed it to be before use_router Router.appRouter to make it similar to c# asp net middlewares pipeline

app.UseResponseCompression();
app.UseStaticFiles();
app.UseMvcWithDefaultRoute();
aspnet/Docs#2516

for me UseMvcWithDefaultRoute and use_router Router.appRouter are in some way related
