### ISSUE TITLE
Unable to setup Saturn on MacOS 

### ISSUE THREAD

**Issue by roebuk** [SaturnFramework/Saturn.Template#20]
Whilst following the '[How to start in 60 seconds](https://saturnframework.org/docs/guides/how-to-start/)' guide, I hit a problem when it's time to run `./build.sh`. I received the following error:

```
➜  SaturnSample ./build.sh
Executing Paket...
paket.lock file found, restoring packages...
./build.sh: line 24: mono: command not found
```

I have dotnet core installed so I attempted to remove the call to  `mono` on line 24 to be simply be `"$@"` and ran `./build.sh` once again. I then hit `./build.sh: line 24: .paket/paket.exe: cannot execute binary file`.

I'm assuming MacOS as possibly Linux aren't currently supported. Are there plans to add support? If so, what would need to be done to allow Saturn's template to work cross platform?

**Versions**
MacOS - 10.14.3
dotnet - 2.2.100
zsh - 5.3

**Update:**

I just installed `mono` and things are working. Perhaps it's worth mentioning that mono is required alongside dotnet. As someone new to dotnet, I thought having dotnet installed would have sufficed. Perhaps this is now simply a documentation issue of required dependencies.

**Comment by Krzysztof-Cieslak** [comment]
Hey, yes - `mono` is required as development time dependency of some tooling we use by default (Paket). This is, hopefully, temporary situation as Paket is going to officially support running on .Net Core soon. 

But documentation update is probably needed, indeed.

**Comment by roebuk** [comment]
@Krzysztof-Cieslak Thanks for the clarification. Would you mind if I took a shot at adding that to the docs?
