### ISSUE TITLE
Template does not build with dotnet --version = 3.0.100

### ISSUE THREAD

**Issue by Freymaurer** [SaturnFramework/Saturn.Template#22]
Hello, i followed the [Using the template](https://github.com/SaturnFramework/Saturn.Template#using-the-template) - guide and i got the following error when trying to build via `fake build`.

    System.IO.FileLoadException: Could not load file or assembly 'System.Threading, Version=4.1.0.0, 
    Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition 
    does not match the assembly reference. (Exception from HRESULT: 0x80131040) at 
    System.Console.get_Out() at Program.main(String[] argv)

I checked my installed sdk versions (`dotnet --info`) and found that i have SDK 2.1.802 installed. This is the version that has LTS as listed [here](https://dotnet.microsoft.com/download/dotnet-core/2.1). At least as far as i understood.

Then i saw that 2.1.508 was referenced in the global.json file so i downloaded that version and tried to build, but it still failed.

In the end i changed the following files:
- global.json -> `"version": "3.0.100"`
- paket.dependencies -> `framework: netcoreapp3.0`
- src/SaturnTemplate/SaturnTemplate.fsproj -> `<TargetFramework>netcoreapp3.0</TargetFramework>`

With these changes the `fake build` and `fake build -t run` command succed.

Now, i am missing a lot of knowledge so i don't know if this is a bug, an missing update or expected behavior and i just did everything wrong. :sweat_smile:

**Comment by mrkaspa** [comment]
Same problem here, is there an update for dotnet 3?

**Comment by andres-k** [comment]
Any update on this?
