### ISSUE TITLE
Fresh app generated from template is missing build.fsx script

### ISSUE THREAD

**Issue by LuisFX** [SaturnFramework/Saturn.Template#39]
![Screen Shot 2022-10-13 at 5 58 11 PM](https://user-images.githubusercontent.com/1130772/195738310-e58c5bc6-e46b-4a3f-a761-0968ab7b5480.png)

Ran the template generator 3 times following the instructions exactly. No build.fs ❓

**Comment by LuisFX** [comment]
Application runs with: dotnet run --project <projectfile>

Is it just a readme.md typo?

**Comment by MangelMaxime** [comment]
I manage to make it working again by manually copying `build.fsx` from the git history.

For example:

https://github.com/SaturnFramework/Saturn.Template/blob/fddf52371ce926fe6319c47f7b0440da176e1416/Content/build.fsx

*I don't know if that build.fsx is the last version of it or not so perhaps you will need to dig to find its latest version*

**Comment by LuisFX** [comment]
Sweet! Thank you, that does work perfectly.
