### ISSUE TITLE
After uncommenting 'suggested' forward "/api" route, left with roadblock

### ISSUE THREAD

**Issue by StachuDotNet** [SaturnFramework/Saturn.Template#6]
I decided to spend an hour tonight to check out Saturn fully. I'm impressed with the work done so far!

In going through the "[60 second guide](https://saturnframework.github.io/docs/guides/how-to-start/)," I've run into a point of confusion:

As of time of this issue, Step 9 tells me the following:

![image](https://user-images.githubusercontent.com/906686/36765395-f9f320b6-1bfe-11e8-8ab7-e95dfbe9368f.png)

Which I take to mean "Uncomment the following line:"
![image](https://user-images.githubusercontent.com/906686/36765420-1c9fd00a-1bff-11e8-9345-4be0e9d66bff.png)

Naturally, when I do such, the apiRouter is undefined, and I need to uncomment the *above* uncommented bits:

![image](https://user-images.githubusercontent.com/906686/36765465-54218d70-1bff-11e8-8f50-f0b42462419f.png)

But when I do that, I see more sad red squigglies :(
Figuring out "how do I implement `error_hander` and `someScopeOrController` certainly goes against the '60 seconds' sales pitch, so the way I see it, this can be solved in one of 2 ways:

1- Remove step 9 from the guide, having the person onboarding interact/learn a bit less
2- Give more instructions as to what should go here.

I suspect that the former is the more obvious choice. Best to leave that sort of stuff for the slightly-longer demo :)

**Comment by rus-vladimir** [comment]
I've tried Saturn yesterday and it literally took 60 sec to bootstrap it. I think you misunderstood the step 9, it was enough to add that line in the existing scope and leave commented part as is:
![2018-03-15_13h34_50](https://user-images.githubusercontent.com/3341799/37461074-f04a32a8-2855-11e8-85e2-06972957d045.png)

**Comment by StachuDotNet** [comment]
Perhaps I did, @rusanov-vladimir!
I'll try this again tonight and verify. If I can get to a working place again, will change some wording to be less confusing for people like me :)
